; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = esp32dev
board = esp32dev
framework = arduino


#include <Arduino.h>

const int PIN_ADC = 34 ;//A ese pin conectaré la señal analógica


void setup() {
  Serial.begin(115200); //Se ejecuta una vez y abre la comunicación por USB  a 115200 baudios
  Serial2.begin(9600, SERIAL_8N1, 16, 17); // Para UART por cada ciclo se envia 8 bits de datos, N no paridad, 1 start bit, 1stop bit --> 10 bits en total
  //Serial2.begin(baudios, formato de envio (UART), RX, TX) ---> FPGA RX=16 recibe datos, TX=17 envia datos
  analogSetAttenuation(ADC_11db); //amplia el rango de lectura de pin para que soporte los 3,3 V
  analogReadResolution(12);// resolución de bits, de 0 hasta 4095
}

void loop() {
  int valor_crudo = analogRead(PIN_ADC);// mide el pin 34 y guarda el numero de 0 a 4095
// 1. Cálculos en voltios puros
  float v_atenuado = valor_crudo * (-3.30 / 4095.0); // regla de 3 para obtener el valor atenuado, se ocupa -3,3 por la inversión de fase
  float v_real = (v_atenuado * (1.0 / 0.44)) - 3.3; // siendo 0,44 la ganancia, la devuelve al valor antes de la atenuacion y considera el offset

  // 2. Escalar a enteros (ej. 3.14V pasa a 314)
  int int_atenuado = abs(v_atenuado * 100);
  int int_real = abs(v_real * 100);
  // guardar digitos 

  uint8_t u_at = (int_atenuado / 100) % 10; // Unidades
  uint8_t d_at = (int_atenuado / 10) % 10;  // Décimas
  uint8_t c_at = int_atenuado % 10;         // Centésimas

  uint8_t u_real = (int_real / 100) % 10;
  uint8_t d_real = (int_real / 10) % 10;
  uint8_t c_real = int_real % 10;

  uint8_t trama[7];
  trama[0] = 0xFF; // byte de inicio, 0xFF es 255   
  trama[1] = u_at;
  trama[2] = d_at;
  trama[3] = c_at;
  trama[4] = u_real;
  trama[5] = d_real;
  trama[6] = c_real;


// Toma la lista "trama" y envía sus 7 bytes consecutivos por el puerto Serial2 (hacia la FPGA).
// El hardware de la ESP32 se encarga automáticamente de agregar los bits de inicio y fin físicos al cable.
  Serial2.write(trama, 7);

  Serial.print(v_atenuado);
  Serial.print(",");
  Serial.println(v_real);


}